apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ui-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: guestbook.shitcloud.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: guestbook-ui
                port:
                  name: http
  tls:
    - secretName: guestbook-secret
      hosts:
        - guestbook.shitcloud.io
      